//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int T_ID { get; set; }
        public string T_Title { get; set; }
        public Nullable<System.DateTime> T_Duedate { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string T_Priority { get; set; }
        public string T_Situation { get; set; }
        public string T_Contents { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
